<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class GoalsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
{
    $goals = [
        [
            'userID' => 1,
            'name' => 'New Room Decoration',
            'amount' => 150.00,
            'currentSave' => 50.00,
            'remainingSave' => 100.00,
            'setDate' => true,
            'startDate' => '2024-01-01',
            'endDate' => '2024-02-29', // Assuming a valid date, change as needed
            'monthlyContribution' => 500.00,// Assuming not applicable when setDate is true
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 1,
            'name' => 'Vacation Fund',
            'amount' => 5000.00,
            'currentSave' => 1000.00,
            'remainingSave' => 4000.00,
            'setDate' => true,
            'startDate' => '2022-01-01',
            'endDate' => '2022-12-31',
            'monthlyContribution' => 250.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 2,
            'name' => 'No Date Fund', // Changed the name to avoid duplication
            'amount' => 5000.00,
            'currentSave' => 1000.00,
            'remainingSave' => 4000.00,
            'setDate' => false,
            'startDate' => null,
            'endDate' => null,
            'monthlyContribution' => 250.00,
            'created_at' => now(),
            'updated_at' => now(), // Since setDate is false, updated_at will be null
        ],
        [
            'userID' => 3,
            'name' => 'Saving Goal',
            'amount' => 200.00,
            'currentSave' => 0.00,
            'remainingSave' => 200.00,
            'setDate' => false,
            'startDate' => null,
            'endDate' => null,
            'monthlyContribution' => 50.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 4,
            'name' => 'Fitness Equipment',
            'amount' => 300.00,
            'currentSave' => 100.00,
            'remainingSave' => 200.00,
            'setDate' => true,
            'startDate' => '2024-02-01',
            'endDate' => '2024-05-31',
            'monthlyContribution' => 50.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 4,
            'name' => 'Emergency Fund',
            'amount' => 1000.00,
            'currentSave' => 500.00,
            'remainingSave' => 500.00,
            'setDate' => true,
            'startDate' => '2024-01-01',
            'endDate' => '2024-12-31',
            'monthlyContribution' => 100.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 8,
            'name' => 'Home Renovation',
            'amount' => 8000.00,
            'currentSave' => 2000.00,
            'remainingSave' => 6000.00,
            'setDate' => true,
            'startDate' => '2023-06-01',
            'endDate' => '2024-12-31',
            'monthlyContribution' => 300.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 6,
            'name' => 'Education Fund',
            'amount' => 12000.00,
            'currentSave' => 3000.00,
            'remainingSave' => 9000.00,
            'setDate' => true,
            'startDate' => '2022-03-15',
            'endDate' => '2024-03-15',
            'monthlyContribution' => 500.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 6,
            'name' => 'Tech Gadgets',
            'amount' => 2000.00,
            'currentSave' => 500.00,
            'remainingSave' => 1500.00,
            'setDate' => true,
            'startDate' => '2023-01-01',
            'endDate' => '2023-12-31',
            'monthlyContribution' => 100.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 3,
            'name' => 'Emergency Medical Fund',
            'amount' => 5000.00,
            'currentSave' => 1000.00,
            'remainingSave' => 4000.00,
            'setDate' => false,
            'startDate' => null,
            'endDate' => null,
            'monthlyContribution' => 0.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 10,
            'name' => 'Gifts for Family',
            'amount' => 300.00,
            'currentSave' => 50.00,
            'remainingSave' => 250.00,
            'setDate' => true,
            'startDate' => '2024-04-01',
            'endDate' => '2024-12-31',
            'monthlyContribution' => 25.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 10,
            'name' => 'Dream Vacation',
            'amount' => 5000.00,
            'currentSave' => 1000.00,
            'remainingSave' => 4000.00,
            'setDate' => true,
            'startDate' => '2023-07-01',
            'endDate' => '2023-12-31',
            'monthlyContribution' => 200.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 2,
            'name' => 'New Laptop',
            'amount' => 2000.00,
            'currentSave' => 400.00,
            'remainingSave' => 1600.00,
            'setDate' => true,
            'startDate' => '2023-05-01',
            'endDate' => '2024-05-01',
            'monthlyContribution' => 150.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 3,
            'name' => 'Home Theater System',
            'amount' => 3000.00,
            'currentSave' => 600.00,
            'remainingSave' => 2400.00,
            'setDate' => true,
            'startDate' => '2023-03-01',
            'endDate' => '2024-03-01',
            'monthlyContribution' => 200.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 7,
            'name' => 'Emergency Travel Fund',
            'amount' => 2500.00,
            'currentSave' => 500.00,
            'remainingSave' => 2000.00,
            'setDate' => true,
            'startDate' => '2023-06-01',
            'endDate' => '2024-06-01',
            'monthlyContribution' => 100.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 8,
            'name' => 'New Wardrobe',
            'amount' => 1000.00,
            'currentSave' => 200.00,
            'remainingSave' => 800.00,
            'setDate' => false,
            'startDate' => null,
            'endDate' => null,
            'monthlyContribution' => 0.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 13,
            'name' => 'Personal Development Course',
            'amount' => 1200.00,
            'currentSave' => 240.00,
            'remainingSave' => 960.00,
            'setDate' => true,
            'startDate' => '2023-04-01',
            'endDate' => '2023-09-01',
            'monthlyContribution' => 80.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 12,
            'name' => 'New Smartphone',
            'amount' => 800.00,
            'currentSave' => 160.00,
            'remainingSave' => 640.00,
            'setDate' => true,
            'startDate' => '2023-07-15',
            'endDate' => '2024-07-15',
            'monthlyContribution' => 80.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 11,
            'name' => 'Charity Donation',
            'amount' => 300.00,
            'currentSave' => 60.00,
            'remainingSave' => 240.00,
            'setDate' => true,
            'startDate' => '2023-01-01',
            'endDate' => '2023-12-31',
            'monthlyContribution' => 20.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 11,
            'name' => 'Test Home Security System',
            'amount' => 1800.00,
            'currentSave' => 360.00,
            'remainingSave' => 1440.00,
            'setDate' => true,
            'startDate' => '2023-08-01',
            'endDate' => '2024-08-01',
            'monthlyContribution' => 120.00,
            //'created_at' => Goal::now()->format('Y-m-d H:i:s'),
            'created_at' => now(),
            'updated_at' => now(),
        ],
    ];
    
    // Insert data into the goals table
    DB::table('goals')->insert($goals);
}

}

